version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "cartyd"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    groups:
      typescript:
        patterns:
          - "@typescript-eslint/*"
          - "typescript"
          - "@types/*"
      testing:
        patterns:
          - "jest"
          - "@types/jest"
          - "ts-jest"
      linting:
        patterns:
          - "eslint*"
          - "prettier"
